const mongoose = require('mongoose');

const productSchema = mongoose.Schema(
    {
        name:{
            type:String,
            required:true,
            trim:true,
        },
        description:{
            type:String,
            required:true,
            trim:true,
        },
        richdescription:{
            type:String,
            default:'',
        },
        image:{
            type:String,
            required:true,
        },
        images:[
            {
                type:String,
            }
        ],
        brand:{
            type:String,
            required:true,
            trim:true
        },
        price:{
            type:Number,
            default:0,
        },
        numreviews:{
            type:Number,
            default:0,
        },
        category:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'category',
            required:true,
        },
        countinstock:{
            type:Number,
            required:true,
            min:0,
            max:100,
        },
        rating:{
            type:Number,
            min:0,
            max:5,
            default:0,
        },
        isfeatured:{
            type:Boolean,
            default:false,
        },
        salescount:{
            type:Number,
            default:0,
        },
        isactive:{
            type:Boolean,
            default:true,
        },
        owner:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'user'
        },
        discount:{
            type:Number,
            min:0,
            max:100,
            default:0
        },
        variants:[
            {
                color:String,
                size:String,
                stock:Number,
                price:Number,
            }
        ]
    },
    {
        timestamps:true,
    }
);

module.exports = mongoose.model("products",productSchema);